// Generated by tools/fx/generate_physicalization_shapes.py.
// Derived cloud mask metrics/checksums only; no commercial images.
static const ShaderShape shaderShapes[] = {
    {"gfx/effects/alpha_smoke", "gfx/effects/alpha_smoke.tga", 0xcb0220b399540940ULL, "shaders/gfx2.shader", 0xe0202970ef242f24ULL, 0.11087048f, 0.83998000f, 0.02312663f},
    {"gfx/effects/alpha_smoke2", "gfx/effects/alpha_smoke2.tga", 0xd6d677f3e8909644ULL, "shaders/gfx2.shader", 0xe0202970ef242f24ULL, 0.09797028f, 0.81519984f, 0.01501129f},
    {"gfx/effects/wcloud", "gfx/effects/wcloud.jpg", 0x2613a0752d76c50aULL, "shaders/effects.shader", 0x9fcb8a0023b7bd43ULL, 0.29686309f, 0.75648240f, 0.02024436f},
    {"gfx/misc/black_smoke", "gfx/effects/black_smoke.tga", 0x0ce5637bd883f5c4ULL, "shaders/effects.shader", 0x9fcb8a0023b7bd43ULL, 0.07007698f, 0.82235609f, 0.01184438f},
    {"gfx/misc/black_smoke2", "gfx/effects/black_smoke2.tga", 0x7dce0e8d0577d02cULL, "shaders/effects.shader", 0x9fcb8a0023b7bd43ULL, 0.07898093f, 0.79334389f, 0.00946975f},
    {"gfx/misc/steam", "gfx/misc/steam.jpg", 0x07802eb583639186ULL, "shaders/effects.shader", 0x9fcb8a0023b7bd43ULL, 0.06101409f, 0.80646799f, 0.00959002f},
};
