#!/usr/bin/env python3
"""Writes test .cube LUTs for rend2 color grading (r_colorGradingLUT).

identity.cube    - neutral LUT, must not change the image
test_look.cube   - deliberately strong look (contrast, teal shadows,
                   orange highlights, less saturation) to verify grading

LUTs map display-encoded sRGB values to display-encoded sRGB values.
Copy the files into a pk3 or the base folder, e.g. base/luts/, and use
r_colorGradingLUT luts/test_look.cube

Usage: make_luts.py [output directory] [size]
"""

import os
import sys


def smoothstep(e0, e1, x):
    t = min(max((x - e0) / (e1 - e0), 0.0), 1.0)
    return t * t * (3.0 - 2.0 * t)


def identity(r, g, b):
    return r, g, b


def test_look(r, g, b):
    luma = 0.2126 * r + 0.7152 * g + 0.0722 * b

    # Contrast around mid grey
    def contrast(c):
        return 0.5 + (c - 0.5) * 1.25

    r, g, b = contrast(r), contrast(g), contrast(b)

    # Teal shadows, orange highlights
    shadow = 1.0 - smoothstep(0.0, 0.5, luma)
    highlight = smoothstep(0.5, 1.0, luma)
    r += -0.06 * shadow + 0.08 * highlight
    g += 0.03 * shadow + 0.02 * highlight
    b += 0.07 * shadow - 0.08 * highlight

    # Desaturate by 30%
    luma = 0.2126 * r + 0.7152 * g + 0.0722 * b
    r, g, b = [luma + 0.7 * (c - luma) for c in (r, g, b)]

    return [min(max(c, 0.0), 1.0) for c in (r, g, b)]


def write_cube(path, title, size, func):
    with open(path, 'w', newline='\n') as f:
        f.write('# Generated by tools/rend2/make_luts.py\n')
        f.write('TITLE "%s"\n' % title)
        f.write('LUT_3D_SIZE %d\n' % size)
        f.write('DOMAIN_MIN 0.0 0.0 0.0\n')
        f.write('DOMAIN_MAX 1.0 1.0 1.0\n')
        # Red changes fastest
        for b in range(size):
            for g in range(size):
                for r in range(size):
                    rgb = func(r / (size - 1), g / (size - 1), b / (size - 1))
                    f.write('%.6f %.6f %.6f\n' % tuple(rgb))


def main():
    out_dir = sys.argv[1] if len(sys.argv) > 1 else '.'
    size = int(sys.argv[2]) if len(sys.argv) > 2 else 33
    os.makedirs(out_dir, exist_ok=True)
    write_cube(os.path.join(out_dir, 'identity.cube'), 'rend2 identity', size, identity)
    write_cube(os.path.join(out_dir, 'test_look.cube'), 'rend2 test look', size, test_look)


if __name__ == '__main__':
    main()
