#!/usr/bin/env python3
"""Generate guarded, reviewed stage-1 profiles from privately installed PK3s.

Only effect/shader identifiers, FNV-1a fingerprints and decisions are emitted;
no commercial effect definitions or textures are redistributed.
"""
import argparse
from pathlib import Path
from audit_stock_fx import Corpus, effects_inventory


# Supported primitive ordinal: exclude ForceFeedback groups ignored by JA.
# Every unspecified primitive/media alternative remains legacy. A material may
# be a {shader: material} map when alternatives of one primitive differ.
REVIEWED = {
    'volumetric/black_smoke': {0: 'DarkSmoke'},
    'volumetric/droid_smoke': {0: 'DarkSmoke'},
    # Light alpha_smoke masks tinted dark->white over life read as grey smoke;
    # only the black_smoke2 mask is a dark absorber.
    'volumetric/black_smoke2': {0: {'gfx/effects/alpha_smoke': 'LightSmoke',
                                    'gfx/effects/alpha_smoke2': 'LightSmoke',
                                    'gfx/misc/black_smoke2': 'DarkSmoke'}},
    'rocket/explosion': {1: 'LightSmoke'},
    'thermal/explosion': {1: 'LightSmoke'},
    'explosions/explosion1': {1: 'LightSmoke'},
    'noghri_stick/gas_cloud': {0: 'Gas'},
    'env/small_fire': {1: 'LightSmoke'},
    'env/small_fire_lod': {1: 'LightSmoke'},
    'env/fire': {1: 'LightSmoke'},
    'env/fire_wall': {1: 'DarkSmoke'},
    'chunks/dustfall': {0: 'DustCloud'},
    # Impact bursts: only the slow 3 s cloud. The 1 s radial puffs and the whole
    # env/slide_dust (spawned every pmove frame, 0.2-0.3 s life) cost proxy
    # budget without visible medium.
    'env/impact_dust': {1: 'DustCloud'},
    'env/impact_dustonly': {1: 'DustCloud'},
    'env/waterfall_mist': {0: 'Mist'},
    'volumetric/large_steam': {0: 'Mist'},
    'volumetric/pressurized_steam': {0: 'Mist'},
    'volumetric/steam': {0: 'Mist', 1: 'Mist'},
    'volumetric/smoke': {0: 'LightSmoke'},
}
ALLOWED = {
    'DarkSmoke': {'gfx/misc/black_smoke', 'gfx/misc/black_smoke2', 'gfx/effects/alpha_smoke', 'gfx/effects/alpha_smoke2'},
    'LightSmoke': {'gfx/misc/steam', 'gfx/effects/alpha_smoke', 'gfx/effects/alpha_smoke2'},
    'Mist': {'gfx/misc/steam'},
    'DustCloud': {'gfx/misc/steam', 'gfx/effects/alpha_smoke', 'gfx/effects/alpha_smoke2'},
    'Gas': {'gfx/effects/wcloud'},
}


def fingerprint(data):
    result = 14695981039346656037
    for value in data:
        result = ((result ^ value) * 1099511628211) & ((1 << 64) - 1)
    return result


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('archives', nargs='+', type=Path)
    ap.add_argument('--out', type=Path, default=Path('shared/fx/FxPhysicalizationStock.h'))
    args = ap.parse_args()
    corpus = Corpus(args.archives)
    try:
        errors = []
        effects = {e['file']: e for e in effects_inventory(corpus, errors)}
        if errors:
            raise ValueError(errors)
        lines = ['// Generated by tools/fx/generate_physicalization_stock.py.',
                 '// Reviewed identifiers and FNV-1a checksums only; no asset contents.',
                 'static const StockRule stockRules[] = {']
        count = 0
        for short, selectors in sorted(REVIEWED.items()):
            name = 'effects/' + short + '.efx'
            effect = effects[name]
            ps = [p for p in effect['primitives'] if p['engine_supported_type']]
            checksum = fingerprint(corpus.read(name))
            for ordinal, material in sorted(selectors.items()):
                primitive = ps[ordinal]
                assert primitive['type'] in ('particle', 'orientedparticle'), (name, ordinal)
                materials = material if isinstance(material, dict) else {s: material for s in primitive['shaders']}
                assert primitive['shaders'] and set(primitive['shaders']) == set(materials), (name, ordinal, primitive['shaders'])
                for shader in primitive['shaders']:
                    material = materials[shader]
                    assert shader in ALLOWED[material], (name, ordinal, shader, material)
                    lines.append('    {"%s", 0x%016xULL, %d, "%s", %s},' % (name, checksum, ordinal, shader, material))
                    count += 1
        lines += ['};', '']
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text('\n'.join(lines), encoding='utf-8')
        print('Generated %d reviewed alternatives across %d effects' % (count, len(REVIEWED)))
    finally:
        corpus.close()


if __name__ == '__main__':
    main()
