#!/usr/bin/env python3
"""Derive bounded cloud support metadata from reviewed installed stock shaders.

No images/EFX are extracted. Requires Pillow. Supply stock PK3s low-to-high.
"""
import argparse
import io
import math
from pathlib import Path
from PIL import Image
from audit_stock_fx import Corpus, shader_inventory, shader_path
from generate_physicalization_stock import fingerprint, ALLOWED


def measure(mask):
    w, h = mask.size
    samples = [(math.hypot((x + .5 - w/2)/(w/2), (y + .5 - h/2)/(h/2)),
                mask.getpixel((x, y))/255) for y in range(h) for x in range(w)]
    total = sum(v for _, v in samples)
    if total <= 0:
        raise ValueError('empty cloud mask')
    accumulated, radius = 0, 0
    for radius, value in sorted(samples):
        accumulated += value
        if accumulated >= total * .9:
            break
    edge = [v for r, v in samples if r > .85]
    return total / len(samples), radius, sum(edge) / max(1, len(edge))


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('archives', nargs='+', type=Path)
    ap.add_argument('--out', type=Path, default=Path('shared/fx/FxPhysicalizationShapes.h'))
    args = ap.parse_args()
    corpus = Corpus(args.archives)
    try:
        errors = []
        shaders = shader_inventory(corpus, errors)
        if errors:
            raise ValueError(errors)
        lines = ['// Generated by tools/fx/generate_physicalization_shapes.py.',
                 '// Derived cloud mask metrics/checksums only; no commercial images.',
                 'static const ShaderShape shaderShapes[] = {']
        for shader in sorted(set().union(*ALLOWED.values())):
            defs = shaders[shader]
            assert len(defs) == 1 and len(defs[0]['stages']) == 1, shader
            definition, stage = defs[0], defs[0]['stages'][0]
            assert len(stage['maps']) == 1, shader
            image = stage['maps'][0]
            base = shader_path(image)
            texture = next(n for n in [image] + [base+e for e in ('.tga', '.jpg', '.png', '.dds')] if n in corpus.index)
            data = corpus.read(texture)
            with Image.open(io.BytesIO(data)) as im:
                use_alpha = 'gl_one_minus_src_alpha' in stage['blend'] and ('A' in im.getbands() or 'transparency' in im.info)
                mask = im.convert('RGBA').getchannel('A') if use_alpha else im.convert('L')
                mask.thumbnail((96, 96))
                mean, radius, edge = measure(mask)
            script = definition['file']
            lines.append('    {"%s", "%s", 0x%016xULL, "%s", 0x%016xULL, %.8ff, %.8ff, %.8ff},' %
                         (shader, texture, fingerprint(data), script, fingerprint(corpus.read(script)), mean, radius, edge))
        lines += ['};', '']
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text('\n'.join(lines), encoding='utf8')
        print('Generated %d reviewed shader shapes' % (len(lines)-5))
    finally:
        corpus.close()


if __name__ == '__main__':
    main()
