# The renderer probes contexts itself, including when loaded by older engines.
function(target_link_renderer_sdl2 target)
    if(UseInternalSDL2)
        if(CMAKE_SIZEOF_VOID_P EQUAL 4)
            set(sdl_arch x86)
        else()
            set(sdl_arch x64)
        endif()
        target_include_directories(${target} PRIVATE "${OpenJKLibDir}/SDL2/include")
        target_link_libraries(${target} "${OpenJKLibDir}/SDL2/lib/${sdl_arch}/SDL2.lib")
    else()
        find_package(SDL2 REQUIRED CONFIG)
        if(TARGET SDL2::SDL2)
            target_link_libraries(${target} SDL2::SDL2)
        else()
            target_include_directories(${target} PRIVATE ${SDL2_INCLUDE_DIRS})
            target_link_libraries(${target} ${SDL2_LIBRARIES})
        endif()
    endif()
endfunction()
